sonar.projectKey=viditdevops_kubernetes-githubactions-kind
sonar.organization=viditdevops

# Scope analysis strictly to your Python application code
sonar.sources=app

# Exclude generated reports, k8s manifests, and non-source files
sonar.exclusions=security-reports/**,k8s/**,*.md,*.yaml,*.yml,*.html,*.json
# Python version
sonar.python.version=3.11
